# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debugWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import time
import openpyxl
class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 522)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        Form.setFont(font)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(100, 20, 256, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(100, 100, 271, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 470, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        ser = serial.Serial()
        ser.baudrate = 115200
        ser.port = 'COM6'
        print(ser)
        ser.open()
        if (ser.is_open):
            print("串口已连接！")
            print("请刷卡考勤，谢谢！")
            s = ser.read(3)
            s1 = s.hex()
            # print(len(s1))
            #print(s1)
            s2 = int(s1[0:6], 16)  # 第一张卡十进制
            s8=str(s2)
            print("考勤成功！您的卡号为：",s2)
            print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
            s6=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

            time.sleep(2)
            print("请刷卡考勤，谢谢！")
            s3 = ser.read(3)
            s4 = s3.hex()
            # print(len(s1))
            #print(s4)
            s5 = int(s4[0:6], 16)  # 第2张卡十进制
            s9=str(s5)
            print("考勤成功！您的卡号为：", s5)
            print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
            s7=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

            wb = openpyxl.Workbook()
            sheet = wb.active

            # 更改默认名称Sheet`
            sheet.title = "门禁考勤表"
            sheet.merge_cells("B1:D1")
            sheet["A1"] = "卡的卡号"
            sheet["B1"] = "刷卡时间"
            sheet["A2"] = s2
            sheet.merge_cells("B2:D2")
            sheet["B2"] = s6
            sheet["A3"] = s5
            sheet.merge_cells("B3:D3")
            sheet["B3"] = s7
            # 保存
            wb.save('考勤表.xlsx')
            print('ok')
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">后台管理</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "卡号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "刷卡成功时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        #写入数据
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", s8))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", s6))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", s9))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", s7))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "返回登录界面"))

